version: '3.7'

services:
  web-app:
    build:
      context: ./app
    ports:
       - 4000:4000
    links:
      - selenium-chrome-node
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  
  selenium-chrome-node:
    build:
      context: ./test
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          
