on:
  push:
    branches:
    - main

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: michelleamesquita/sast:latest
    steps:
         - name: Start SAST
           run: docker run -v $PWD/:/app michelleamesquita/sast -d=./app -l=python
#            uses: docker://michelleamesquita/sast:latest
#            with:
#              options: -v $PWD/:/app
#              args: -d=./app/ -l=python
             
             
