name: full-security-scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issue_comment:
    types: [created]


jobs:

  semgrep:
    runs-on: ubuntu-20.04
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
            p/django
            p/owasp-top-ten
        continue-on-error: true
          
  
