
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to validate SAST
    steps:
      - name: SAST
        uses: michelleamesquita/sast-validator@v1
        with:
          path: ./app
          language: python
