on:
  push:
    branches:
    - main

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: michelleamesquita/sast:latest
    steps:
         - name: Start SAST
           uses: docker://michelleamesquita/sast:latest
           with:
             volumes: -v $PWD/:/app
             args: -d=./app/ -l=python
             
             
