name: full-security-scan
on:
  push:
    branches: [ semgrep-tool ]
  pull_request:
    branches: [ semgrep-tool ]
  issue_comment:
    types: [created]


jobs:

  semgrep:
    runs-on: ubuntu-latest
    container: 
        image: returntocorp/semgrep-agent:v1
    steps:
      - name: Run Commands
        run: semgrep-agent --config "p/owasp-top-ten" --gitlab-json > semgrep_report.json
         
        continue-on-error: true


      # - uses: returntocorp/semgrep-action@v1
      #   with:
      #     config: >- # more at semgrep.dev/explore
      #       p/security-audit
      #       p/secrets
      #       p/django
      #       p/owasp-top-ten
      #   continue-on-error: true

      - name: Archive semgrep report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep_report
          path: ./semgrep_report.json
          
  
