
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SAST Validator
    steps:
      - uses: michelleamesquita/sast-validator@v1
        with:
          path: ./app
          language: python
