
on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SAST Validator
    steps:
      - uses: actions/checkout@v2
      - uses: michelleamesquita/sast-validator@v9
        with:
          path: ./app/
          language: python
