
on:
  push:
    branches:
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SAST Validator
    steps:
      - name: SAST validator
        uses: michelleamesquita/sast-validator@v36
        with:
          path: ./app/
          language: python
